class XETesterAuto{
constructor(){this.index=null;this.pad=null;this.last=0;this.hz=[];this.phase="sticks";this.finished=false;this.profile=null;this.data={ls:this.stickData(),rs:this.stickData(),lt:{hits:0,armed:true,max:0,jitter:0,last:0},rt:{hits:0,armed:true,max:0,jitter:0,last:0},buttons:{},findings:[],score:100};this.names=["A","B","X","Y","LB","RB","VIEW","MENU","LS","RS","UP","DOWN","LEFT","RIGHT","GUIDE"];this.buttonMap={A:0,B:1,X:2,Y:3,LB:4,RB:5,VIEW:8,MENU:9,LS:10,RS:11,UP:12,DOWN:13,LEFT:14,RIGHT:15,GUIDE:16};this.initButtons();this.bind();this.loop()}
stickData(){return{max:0,centerMax:0,bins:new Set(),centerFrames:0,samples:0,x:0,y:0}}
initButtons(){let g=document.getElementById("buttonGrid");this.names.forEach(n=>{this.data.buttons[n]=false;g.insertAdjacentHTML("beforeend",`<div class="buttonItem" id="bi-${n}"><span>${n}</span><b>○</b></div>`)})}
bind(){window.addEventListener("gamepadconnected",e=>this.consider(e.gamepad,true));window.addEventListener("gamepaddisconnected",e=>{if(e.gamepad.index===this.index)this.disconnect()});document.addEventListener("visibilitychange",()=>{if(!document.hidden)this.scan()});window.addEventListener("focus",()=>this.scan());document.getElementById("rawToggle").onclick=()=>document.getElementById("rawData").classList.toggle("hidden");document.getElementById("restart").onclick=()=>location.reload();document.getElementById("pdf").onclick=()=>this.pdf();document.getElementById("workshop").onclick=()=>this.whatsapp()}
loop(t=0){this.scan();if(this.pad){let pads=navigator.getGamepads?.()||[];let p=pads[this.index];if(p){this.pad=p;this.update(t,p)}}requestAnimationFrame(x=>this.loop(x))}
scan(){let pads=navigator.getGamepads?.()||[];if(this.index!==null&&pads[this.index])return;for(let p of pads){if(p&&this.hasInput(p)){this.consider(p);break}}}
hasInput(p){return p.buttons.some(b=>b.pressed||b.value>.15)||p.axes.some(a=>Math.abs(a)>.25)}
consider(p){if(this.index!==null)return;this.index=p.index;this.pad=p;this.profile=this.resolveProfile(p);document.getElementById("connection").classList.replace("off","on");document.getElementById("status").textContent="Control conectado · diagnóstico en curso";document.getElementById("devName").textContent=this.profile.name;document.getElementById("devMap").textContent=p.mapping||"raw/no estándar";document.getElementById("devIO").textContent=`${p.buttons.length} / ${p.axes.length}`;document.getElementById("profile").textContent=this.profile.note;document.getElementById("mappingBadge").textContent=this.profile.label;document.getElementById("liveProfile").textContent=this.profile.label}
resolveProfile(p){let id=(p.id||"").toLowerCase();if(id.includes("elite")||id.includes("0b00")||id.includes("02e3"))return{name:"Xbox Elite Series 2",label:"ELITE S2",note:"Perfil Xbox Elite Series 2 · lectura normalizada Gamepad API",map:{...this.buttonMap},axes:[0,1,2,3],triggers:[6,7]};if(id.includes("xbox")||id.includes("xinput")||id.includes("045e"))return{name:"Control Xbox / XInput",label:"XBOX",note:"Perfil estándar Xbox / XInput",map:{...this.buttonMap},axes:[0,1,2,3],triggers:[6,7]};if(id.includes("dualsense")||id.includes("dualshock")||id.includes("playstation")||id.includes("054c"))return{name:"Control PlayStation",label:"PLAYSTATION",note:"Perfil estándar normalizado por navegador",map:{...this.buttonMap},axes:[0,1,2,3],triggers:[6,7]};return{name:this.cleanName(p.id),label:p.mapping==="standard"?"STANDARD":"RAW",note:p.mapping==="standard"?"Mapeo estándar del navegador":"Control no estándar: monitor RAW activo para verificación",map:{...this.buttonMap},axes:[0,1,2,3],triggers:[6,7]}}
cleanName(id){return(id||"Control genérico").replace(/\([^)]*\)/g,"").slice(0,70)}
disconnect(){this.index=null;this.pad=null;document.getElementById("connection").classList.replace("on","off");document.getElementById("status").textContent="Control desconectado"}
update(t,p){let dt=t-this.last;if(dt>0&&this.last){this.hz.push(1000/dt);if(this.hz.length>60)this.hz.shift();document.getElementById("polling").textContent=Math.round(this.hz.reduce((a,b)=>a+b,0)/this.hz.length)+" Hz"}this.last=t;let ax=this.profile.axes.map(i=>p.axes[i]??0),lt=this.readTrigger(p,this.profile.triggers[0]),rt=this.readTrigger(p,this.profile.triggers[1]);this.live(ax,lt,rt,p);this.raw(p);if(this.finished)return;if(this.phase==="sticks")this.testSticks(ax);else if(this.phase==="triggers")this.testTriggers(lt,rt);else if(this.phase==="buttons")this.testButtons(p)}
readTrigger(p,i){let b=p.buttons[i];return b?Math.max(0,Math.min(1,b.value??(b.pressed?1:0))):0}
live(a,lt,rt,p){document.getElementById("liveLS").textContent=`${a[0].toFixed(3)} / ${a[1].toFixed(3)}`;document.getElementById("liveRS").textContent=`${a[2].toFixed(3)} / ${a[3].toFixed(3)}`;document.getElementById("liveLT").textContent=lt.toFixed(3);document.getElementById("liveRT").textContent=rt.toFixed(3);document.querySelector("#stickL i").style.transform=`translate(${a[0]*10}px,${a[1]*10}px)`;document.querySelector("#stickR i").style.transform=`translate(${a[2]*10}px,${a[3]*10}px)`;for(let [n,i] of Object.entries(this.profile.map)){let el=document.querySelector(`[data-v="${n}"]`);if(el)el.classList.toggle("pressed",!!p.buttons[i]?.pressed)}}
raw(p){document.getElementById("rawData").innerHTML=`ID: ${this.escape(p.id)}<br>mapping: ${p.mapping||"(vacío)"}<br>buttons(${p.buttons.length}): ${p.buttons.map((b,i)=>`${i}:${b.value.toFixed(3)}${b.pressed?"*":""}`).join(" | ")}<br>axes(${p.axes.length}): ${p.axes.map((a,i)=>`${i}:${a.toFixed(4)}`).join(" | ")}`}
testSticks(a){this.sampleStick("ls",a[0],a[1],"ls");this.sampleStick("rs",a[2],a[3],"rs");if(this.stickReady(this.data.ls)&&this.stickReady(this.data.rs))this.next("triggers")}
sampleStick(k,x,y,prefix){let d=this.data[k],dist=Math.hypot(x,y);d.x=x;d.y=y;d.samples++;d.max=Math.max(d.max,dist);if(dist<.22){d.centerFrames++;d.centerMax=Math.max(d.centerMax,dist)}if(dist>.65){let angle=(Math.atan2(y,x)+Math.PI*2)%(Math.PI*2);d.bins.add(Math.floor(angle/(Math.PI*2)*16))}let drift=d.centerFrames?d.centerMax*100:dist*100;document.getElementById(prefix+"Drift").textContent=drift.toFixed(2)+"%";document.getElementById(prefix+"Range").textContent=Math.min(100,d.max*100).toFixed(0)+"%";document.getElementById(prefix+"Coverage").textContent=Math.round(d.bins.size/16*100)+"%";this.draw(prefix,x,y,d.bins)}
stickReady(d){return d.max>.82&&d.bins.size>=12&&d.centerFrames>=25}
draw(id,x,y,bins){let c=document.getElementById(id),q=c.getContext("2d"),cx=110,cy=110,r=94;q.clearRect(0,0,220,220);q.strokeStyle="rgba(138,249,255,.16)";q.lineWidth=1;q.beginPath();q.arc(cx,cy,r,0,Math.PI*2);q.stroke();q.beginPath();q.moveTo(cx,8);q.lineTo(cx,212);q.moveTo(8,cy);q.lineTo(212,cy);q.stroke();for(let b of bins){let an=(b+.5)/16*Math.PI*2;q.strokeStyle="rgba(37,228,154,.45)";q.beginPath();q.arc(cx,cy,r-4,an-.12,an+.12);q.stroke()}q.strokeStyle="#1ce7f2";q.beginPath();q.moveTo(cx,cy);q.lineTo(cx+x*r,cy+y*r);q.stroke();q.fillStyle="#8af9ff";q.shadowBlur=15;q.shadowColor="#1ce7f2";q.beginPath();q.arc(cx+x*r,cy+y*r,7,0,Math.PI*2);q.fill();q.shadowBlur=0}
testTriggers(lt,rt){this.trigger("lt",lt);this.trigger("rt",rt);if(this.data.lt.hits>=3&&this.data.rt.hits>=3)this.next("buttons")}
trigger(k,v){let d=this.data[k];d.max=Math.max(d.max,v);if(Math.abs(v-d.last)>.08&&Math.abs(v-d.last)<.8)d.jitter++;if(d.armed&&v>.94){d.hits++;d.armed=false}if(v<.1)d.armed=true;d.last=v;document.getElementById(k+"Bar").style.width=(v*100)+"%";document.getElementById(k+"Pct").textContent=(v*100).toFixed(0)+"%";document.getElementById(k+"Hits").textContent=Math.min(d.hits,3)+" / 3 recorridos"}
testButtons(p){for(let [n,i] of Object.entries(this.profile.map)){if(!this.data.buttons.hasOwnProperty(n))continue;if(p.buttons[i]?.pressed){this.data.buttons[n]=true;let el=document.getElementById("bi-"+n);el.classList.add("hit");el.querySelector("b").textContent="✓"}}if(this.names.every(n=>this.data.buttons[n]))this.finish()}
next(phase){document.getElementById("test-"+this.phase).classList.remove("active");document.getElementById("test-"+this.phase).classList.add("complete");document.getElementById("state-"+this.phase).textContent="COMPLETADO ✓";document.querySelector(`[data-step="${this.phase}"]`).classList.add("done");this.phase=phase;document.getElementById("test-"+phase).classList.remove("locked");document.getElementById("test-"+phase).classList.add("active");document.getElementById("state-"+phase).textContent="EN PRUEBA";document.querySelector(`[data-step="${phase}"]`).classList.add("active");document.getElementById("test-"+phase).scrollIntoView({behavior:"smooth",block:"center"})}
finish(){document.getElementById("test-buttons").classList.add("complete");document.getElementById("state-buttons").textContent="COMPLETADO ✓";document.querySelector('[data-step="buttons"]').classList.add("done");this.finished=true;this.phase="result";this.calculate();document.querySelector('[data-step="result"]').classList.add("active");document.getElementById("result").classList.remove("hidden");document.getElementById("result").scrollIntoView({behavior:"smooth",block:"center"})}
calculate(){let score=100,f=[];let ld=this.data.ls.centerMax*100,rd=this.data.rs.centerMax*100;if(ld>5){score-=Math.min(25,(ld-5)*2);f.push(["bad",`Joystick izquierdo: drift máximo de retorno ${ld.toFixed(2)}%.`])}else f.push(["",`Joystick izquierdo: retorno al centro dentro del rango XE (${ld.toFixed(2)}%).`]);if(rd>5){score-=Math.min(25,(rd-5)*2);f.push(["bad",`Joystick derecho: drift máximo de retorno ${rd.toFixed(2)}%.`])}else f.push(["",`Joystick derecho: retorno al centro dentro del rango XE (${rd.toFixed(2)}%).`]);for(let k of ["lt","rt"]){let d=this.data[k];if(d.max<.94){score-=12;f.push(["bad",`${k.toUpperCase()}: pérdida de rango, máximo ${(d.max*100).toFixed(1)}%.`])}else f.push(["",`${k.toUpperCase()}: recorrido completo verificado.`]);if(d.jitter>35){score-=8;f.push(["bad",`${k.toUpperCase()}: variación/ruido elevado detectado.`])}}score=Math.max(0,Math.round(score));let cl=score>=90?"EXCELENTE":score>=80?"MUY BUENO":score>=70?"BUENO":score>=60?"REGULAR":score>=40?"MALO":"REQUIERE REPARACIÓN";this.data.score=score;this.data.classification=cl;this.data.findings=f;document.getElementById("score").textContent=score;document.getElementById("classification").textContent=cl;document.getElementById("summary").textContent=score>=80?"El control completó todas las pruebas automáticas. Revisa el detalle técnico.":"Se detectaron valores que justifican revisión técnica.";document.getElementById("findings").innerHTML=f.map(x=>`<div class="finding ${x[0]}">${x[1]}</div>`).join("");this.pdf(true)}
async pdf(auto=false){let name=document.getElementById("clientName").value||"No especificado",serial=document.getElementById("serial").value||"No especificado";if(!window.jspdf){if(!auto)window.print();return}let {jsPDF}=window.jspdf,doc=new jsPDF(),y=20;doc.setFont("helvetica","bold");doc.setFontSize(20);doc.text("XE TESTER PRO",20,y);y+=9;doc.setFontSize(11);doc.text("REPORTE DE DIAGNOSTICO AUTOMATICO",20,y);y+=12;doc.setFont("helvetica","normal");let lines=[`Fecha: ${new Date().toLocaleString("es-MX")}`,`Cliente: ${name}`,`Serie / folio: ${serial}`,`Control: ${this.profile.name}`,`Perfil: ${this.profile.label}`,`Mapeo navegador: ${this.pad.mapping||"raw/no estandar"}`,`XE SCORE: ${this.data.score}/100 - ${this.data.classification}`,"",`LS drift retorno: ${(this.data.ls.centerMax*100).toFixed(2)}% | rango: ${(this.data.ls.max*100).toFixed(1)}%`,`RS drift retorno: ${(this.data.rs.centerMax*100).toFixed(2)}% | rango: ${(this.data.rs.max*100).toFixed(1)}%`,`LT maximo: ${(this.data.lt.max*100).toFixed(1)}% | recorridos: ${this.data.lt.hits}`,`RT maximo: ${(this.data.rt.max*100).toFixed(1)}% | recorridos: ${this.data.rt.hits}`,"","HALLAZGOS:"];for(let s of lines){doc.text(s,20,y);y+=7}for(let x of this.data.findings){let a=doc.splitTextToSize("- "+x[1],165);doc.text(a,20,y);y+=a.length*6}y+=6;doc.setFont("helvetica","bold");doc.text("XE Servicio Electronico | Chilpancingo, Guerrero",20,y);this.pdfDoc=doc;if(!auto)doc.save(`XE-Diagnostico-${Date.now()}.pdf`)}
whatsapp(){let f=this.data.findings.filter(x=>x[0]==="bad").map(x=>"• "+x[1]).join("\n")||"• Sin fallas críticas detectadas.";let msg=`🎮 *DIAGNÓSTICO XE TESTER PRO*\n\nControl: ${this.profile.name}\nPerfil: ${this.profile.label}\nXE Score: ${this.data.score}/100 - ${this.data.classification}\n\n*Resultado:*\n${f}\n\nSolicito revisión / seguimiento en XE Servicio Electrónico.\n\n📎 Adjuntaré el PDF generado por XE Tester Pro en este chat.`;window.open(`https://api.whatsapp.com/send?phone=527471731852&text=${encodeURIComponent(msg)}`,"_blank")}
escape(s){return String(s).replace(/[&<>]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[m]))}}
new XETesterAuto();